Repository haskell/haskell-ide-engine, pull requests merged in 2018-11, with the labels that each got.

#925 Bump stack resolvers
  stack-8.4.4.yaml
  stack.yaml
Labels: build

#783 Use Brittany with hsimport when needed
  app/MainHie.hs
  haskell-ide-engine.cabal
  hie-plugin-api/Haskell/Ide/Engine/Config.hs
  hie-plugin-api/Haskell/Ide/Engine/IdeFunctions.hs
  hie-plugin-api/Haskell/Ide/Engine/Monad.hs
  hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs
  hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs
  hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
  hie-plugin-api/hie-plugin-api.cabal
  src/Haskell/Ide/Engine/LSP/CodeActions.hs
  src/Haskell/Ide/Engine/LSP/Reactor.hs
  src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs
  src/Haskell/Ide/Engine/Plugin/Base.hs
  src/Haskell/Ide/Engine/Plugin/Brittany.hs
  src/Haskell/Ide/Engine/Plugin/Build.hs
  src/Haskell/Ide/Engine/Plugin/Example2.hs
  src/Haskell/Ide/Engine/Plugin/GhcMod.hs
  src/Haskell/Ide/Engine/Plugin/HaRe.hs
  src/Haskell/Ide/Engine/Plugin/HfaAlign.hs
  src/Haskell/Ide/Engine/Plugin/HieExtras.hs
  src/Haskell/Ide/Engine/Plugin/Hoogle.hs
  src/Haskell/Ide/Engine/Plugin/HsImport.hs
  src/Haskell/Ide/Engine/Plugin/Liquid.hs
  src/Haskell/Ide/Engine/Plugin/Package.hs
  src/Haskell/Ide/Engine/Plugin/Pragmas.hs
  src/Haskell/Ide/Engine/Scheduler.hs
  src/Haskell/Ide/Engine/Transport/JsonStdio.hs
  src/Haskell/Ide/Engine/Transport/LspStdio.hs
  test/dispatcher/Main.hs
  test/functional/FunctionalCodeActionsSpec.hs
  test/functional/FunctionalLiquidSpec.hs
  test/plugin-dispatcher/Main.hs
  test/testdata/CodeActionImportBrittany.hs
  test/unit/ApplyRefactPluginSpec.hs
  test/unit/BrittanySpec.hs
  test/unit/ExtensibleStateSpec.hs
  test/unit/GhcModPluginSpec.hs
  test/unit/HaRePluginSpec.hs
  test/unit/HooglePluginSpec.hs
  test/unit/JsonSpec.hs
  test/utils/TestUtils.hs
Labels: type: enhancement, type: refactor

#932 Replace bat script with PowerShell, update Windows instructions in README
  README.md
  build-all.ps1
  make-build-all.bat
Labels: os: windows

#937 Fix lints on LspStdio
  src/Haskell/Ide/Engine/Transport/LspStdio.hs
Labels: gardening 🌱

#934 Add dist command to makefile
  Makefile
Labels: build
