Repository haskell/haskell-ide-engine, pull requests merged in 2019-04, with the labels that each got.

#1163 Only plugins in the Haskell.Ide.Engine.Plugin module space
  haskell-ide-engine.cabal
  src/Haskell/Ide/Engine/Plugin/Brittany.hs
  src/Haskell/Ide/Engine/Plugin/GhcMod.hs
  src/Haskell/Ide/Engine/Plugin/HaRe.hs
  src/Haskell/Ide/Engine/Plugin/Haddock.hs
  src/Haskell/Ide/Engine/Support/Fuzzy.hs
  src/Haskell/Ide/Engine/Support/HieExtras.hs
  src/Haskell/Ide/Engine/Transport/LspStdio.hs
  test/dispatcher/Main.hs
  test/unit/GhcModPluginSpec.hs
  test/unit/HaRePluginSpec.hs
  test/unit/JsonSpec.hs
Labels: gardening 🌱, type: refactor

#1165 Document formatters
  hie-plugin-api/Haskell/Ide/Engine/PluginsIdeMonads.hs
  src/Haskell/Ide/Engine/Plugin/Brittany.hs
  src/Haskell/Ide/Engine/Plugin/Floskell.hs
Labels: gardening 🌱

#1173 Document Hoogle Plugin
  src/Haskell/Ide/Engine/Plugin/Hoogle.hs
Labels: gardening 🌱

#1168 Build simplifications
  README.md
  install.hs
Labels: build, gardening 🌱
